/**
 * newlife-creator-api-eu-dev
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2022-05-20T13:39:48Z
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.27.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * BcApproveDaoProposalRequest.h
 *
 * 
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_BcApproveDaoProposalRequest_H_
#define IO_SWAGGER_CLIENT_MODEL_BcApproveDaoProposalRequest_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  BcApproveDaoProposalRequest
    : public ModelBase
{
public:
    BcApproveDaoProposalRequest();
    virtual ~BcApproveDaoProposalRequest();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// BcApproveDaoProposalRequest members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getApprover() const;
    bool approverIsSet() const;
    void unsetApprover();
    void setApprover(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getProposalAuthor() const;
    bool proposalAuthorIsSet() const;
    void unsetProposal_author();
    void setProposalAuthor(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getProposalId() const;
    bool proposalIdIsSet() const;
    void unsetProposal_id();
    void setProposalId(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    double getDaoId() const;
    bool daoIdIsSet() const;
    void unsetDao_id();
    void setDaoId(double value);
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getDaoOwner() const;
    bool daoOwnerIsSet() const;
    void unsetDao_owner();
    void setDaoOwner(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getApproverPrvKey() const;
    bool approverPrvKeyIsSet() const;
    void unsetApprover_prv_key();
    void setApproverPrvKey(utility::string_t value);

protected:
    utility::string_t m_Approver;
    bool m_ApproverIsSet;
    utility::string_t m_Proposal_author;
    bool m_Proposal_authorIsSet;
    utility::string_t m_Proposal_id;
    bool m_Proposal_idIsSet;
    double m_Dao_id;
    bool m_Dao_idIsSet;
    utility::string_t m_Dao_owner;
    bool m_Dao_ownerIsSet;
    utility::string_t m_Approver_prv_key;
    bool m_Approver_prv_keyIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_BcApproveDaoProposalRequest_H_ */
