/**
 * newlife-creator-api-eu-dev
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2022-06-09T06:13:03Z
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.27.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * BcDaoProposalExecuteRequest.h
 *
 * BcDaoProposalExecuteRequest Model
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_BcDaoProposalExecuteRequest_H_
#define IO_SWAGGER_CLIENT_MODEL_BcDaoProposalExecuteRequest_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// BcDaoProposalExecuteRequest Model
/// </summary>
class  BcDaoProposalExecuteRequest
    : public ModelBase
{
public:
    BcDaoProposalExecuteRequest();
    virtual ~BcDaoProposalExecuteRequest();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// BcDaoProposalExecuteRequest members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getProposalAuthor() const;
    bool proposalAuthorIsSet() const;
    void unsetProposal_author();
    void setProposalAuthor(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    double getProposalId() const;
    bool proposalIdIsSet() const;
    void unsetProposal_id();
    void setProposalId(double value);
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getDaoId() const;
    bool daoIdIsSet() const;
    void unsetDao_id();
    void setDaoId(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getDaoOwner() const;
    bool daoOwnerIsSet() const;
    void unsetDao_owner();
    void setDaoOwner(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getExec() const;
    bool execIsSet() const;
    void unsetExec();
    void setExec(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getExecPrvKey() const;
    bool execPrvKeyIsSet() const;
    void unsetExec_prv_key();
    void setExecPrvKey(utility::string_t value);

protected:
    utility::string_t m_Proposal_author;
    bool m_Proposal_authorIsSet;
    double m_Proposal_id;
    bool m_Proposal_idIsSet;
    utility::string_t m_Dao_id;
    bool m_Dao_idIsSet;
    utility::string_t m_Dao_owner;
    bool m_Dao_ownerIsSet;
    utility::string_t m_Exec;
    bool m_ExecIsSet;
    utility::string_t m_Exec_prv_key;
    bool m_Exec_prv_keyIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_BcDaoProposalExecuteRequest_H_ */
