/* 
 * newlife-creator-api-eu-dev
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2022-06-09T06:13:03Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BcDaoProposalExecuteResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BcDaoProposalExecuteResponseTests
    {
        // TODO uncomment below to declare an instance variable for BcDaoProposalExecuteResponse
        //private BcDaoProposalExecuteResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BcDaoProposalExecuteResponse
            //instance = new BcDaoProposalExecuteResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BcDaoProposalExecuteResponse
        /// </summary>
        [Test]
        public void BcDaoProposalExecuteResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BcDaoProposalExecuteResponse
            //Assert.IsInstanceOfType<BcDaoProposalExecuteResponse> (instance, "variable 'instance' is a BcDaoProposalExecuteResponse");
        }


        /// <summary>
        /// Test the property 'TxIDExecuteDaoProposal'
        /// </summary>
        [Test]
        public void TxIDExecuteDaoProposalTest()
        {
            // TODO unit test for the property 'TxIDExecuteDaoProposal'
        }

    }

}
