/* 
 * newlife-creator-api-eu-dev
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2022-05-20T13:39:48Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PostCreateResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PostCreateResponseTests
    {
        // TODO uncomment below to declare an instance variable for PostCreateResponse
        //private PostCreateResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PostCreateResponse
            //instance = new PostCreateResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PostCreateResponse
        /// </summary>
        [Test]
        public void PostCreateResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PostCreateResponse
            //Assert.IsInstanceOfType<PostCreateResponse> (instance, "variable 'instance' is a PostCreateResponse");
        }


        /// <summary>
        /// Test the property 'CoverContentUrl'
        /// </summary>
        [Test]
        public void CoverContentUrlTest()
        {
            // TODO unit test for the property 'CoverContentUrl'
        }
        /// <summary>
        /// Test the property 'MoodId'
        /// </summary>
        [Test]
        public void MoodIdTest()
        {
            // TODO unit test for the property 'MoodId'
        }
        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Test]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }
        /// <summary>
        /// Test the property 'Author'
        /// </summary>
        [Test]
        public void AuthorTest()
        {
            // TODO unit test for the property 'Author'
        }
        /// <summary>
        /// Test the property 'Latitude'
        /// </summary>
        [Test]
        public void LatitudeTest()
        {
            // TODO unit test for the property 'Latitude'
        }
        /// <summary>
        /// Test the property 'Moods'
        /// </summary>
        [Test]
        public void MoodsTest()
        {
            // TODO unit test for the property 'Moods'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'AspectRatio'
        /// </summary>
        [Test]
        public void AspectRatioTest()
        {
            // TODO unit test for the property 'AspectRatio'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Test]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }
        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Test]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }
        /// <summary>
        /// Test the property 'License'
        /// </summary>
        [Test]
        public void LicenseTest()
        {
            // TODO unit test for the property 'License'
        }
        /// <summary>
        /// Test the property 'ContentUrl'
        /// </summary>
        [Test]
        public void ContentUrlTest()
        {
            // TODO unit test for the property 'ContentUrl'
        }
        /// <summary>
        /// Test the property 'BlurHash'
        /// </summary>
        [Test]
        public void BlurHashTest()
        {
            // TODO unit test for the property 'BlurHash'
        }
        /// <summary>
        /// Test the property 'NewcoinMintTx'
        /// </summary>
        [Test]
        public void NewcoinMintTxTest()
        {
            // TODO unit test for the property 'NewcoinMintTx'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ConsentEmail'
        /// </summary>
        [Test]
        public void ConsentEmailTest()
        {
            // TODO unit test for the property 'ConsentEmail'
        }
        /// <summary>
        /// Test the property 'Updated'
        /// </summary>
        [Test]
        public void UpdatedTest()
        {
            // TODO unit test for the property 'Updated'
        }
        /// <summary>
        /// Test the property 'ContentType'
        /// </summary>
        [Test]
        public void ContentTypeTest()
        {
            // TODO unit test for the property 'ContentType'
        }
        /// <summary>
        /// Test the property 'Longitude'
        /// </summary>
        [Test]
        public void LongitudeTest()
        {
            // TODO unit test for the property 'Longitude'
        }

    }

}
