# coding: utf-8

"""
    newlife-creator-api-eu-dev

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2022-06-09T06:13:03Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class PagedRatedResponsePostRel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'score': 'float',
        'source': 'str',
        'category': 'str'
    }

    attribute_map = {
        'score': 'score',
        'source': 'source',
        'category': 'category'
    }

    def __init__(self, score=None, source=None, category=None, _configuration=None):  # noqa: E501
        """PagedRatedResponsePostRel - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._score = None
        self._source = None
        self._category = None
        self.discriminator = None

        if score is not None:
            self.score = score
        if source is not None:
            self.source = source
        if category is not None:
            self.category = category

    @property
    def score(self):
        """Gets the score of this PagedRatedResponsePostRel.  # noqa: E501


        :return: The score of this PagedRatedResponsePostRel.  # noqa: E501
        :rtype: float
        """
        return self._score

    @score.setter
    def score(self, score):
        """Sets the score of this PagedRatedResponsePostRel.


        :param score: The score of this PagedRatedResponsePostRel.  # noqa: E501
        :type: float
        """

        self._score = score

    @property
    def source(self):
        """Gets the source of this PagedRatedResponsePostRel.  # noqa: E501


        :return: The source of this PagedRatedResponsePostRel.  # noqa: E501
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this PagedRatedResponsePostRel.


        :param source: The source of this PagedRatedResponsePostRel.  # noqa: E501
        :type: str
        """

        self._source = source

    @property
    def category(self):
        """Gets the category of this PagedRatedResponsePostRel.  # noqa: E501


        :return: The category of this PagedRatedResponsePostRel.  # noqa: E501
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category):
        """Sets the category of this PagedRatedResponsePostRel.


        :param category: The category of this PagedRatedResponsePostRel.  # noqa: E501
        :type: str
        """

        self._category = category

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PagedRatedResponsePostRel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PagedRatedResponsePostRel):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PagedRatedResponsePostRel):
            return True

        return self.to_dict() != other.to_dict()
