# coding: utf-8

"""
    newlife-creator-api-eu-dev

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2022-05-20T13:39:48Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class UserUpdateRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'last_name': 'str',
        'website': 'str',
        'consent_privacy_policy': 'str',
        'display_name': 'str',
        'latitude': 'float',
        'newcoin_create_account': 'str',
        'full_name': 'str',
        'tumblr': 'str',
        'description': 'str',
        'instagram': 'str',
        'soundcloud': 'str',
        'first_name': 'str',
        'twitter': 'str',
        'tiktok': 'str',
        'id': 'str',
        'consent_email': 'str',
        'longitude': 'float'
    }

    attribute_map = {
        'last_name': 'lastName',
        'website': 'website',
        'consent_privacy_policy': 'consentPrivacyPolicy',
        'display_name': 'displayName',
        'latitude': 'latitude',
        'newcoin_create_account': 'newcoinCreateAccount',
        'full_name': 'fullName',
        'tumblr': 'tumblr',
        'description': 'description',
        'instagram': 'instagram',
        'soundcloud': 'soundcloud',
        'first_name': 'firstName',
        'twitter': 'twitter',
        'tiktok': 'tiktok',
        'id': 'id',
        'consent_email': 'consentEmail',
        'longitude': 'longitude'
    }

    def __init__(self, last_name=None, website=None, consent_privacy_policy=None, display_name=None, latitude=None, newcoin_create_account=None, full_name=None, tumblr=None, description=None, instagram=None, soundcloud=None, first_name=None, twitter=None, tiktok=None, id=None, consent_email=None, longitude=None, _configuration=None):  # noqa: E501
        """UserUpdateRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._last_name = None
        self._website = None
        self._consent_privacy_policy = None
        self._display_name = None
        self._latitude = None
        self._newcoin_create_account = None
        self._full_name = None
        self._tumblr = None
        self._description = None
        self._instagram = None
        self._soundcloud = None
        self._first_name = None
        self._twitter = None
        self._tiktok = None
        self._id = None
        self._consent_email = None
        self._longitude = None
        self.discriminator = None

        if last_name is not None:
            self.last_name = last_name
        if website is not None:
            self.website = website
        if consent_privacy_policy is not None:
            self.consent_privacy_policy = consent_privacy_policy
        if display_name is not None:
            self.display_name = display_name
        if latitude is not None:
            self.latitude = latitude
        if newcoin_create_account is not None:
            self.newcoin_create_account = newcoin_create_account
        if full_name is not None:
            self.full_name = full_name
        if tumblr is not None:
            self.tumblr = tumblr
        if description is not None:
            self.description = description
        if instagram is not None:
            self.instagram = instagram
        if soundcloud is not None:
            self.soundcloud = soundcloud
        if first_name is not None:
            self.first_name = first_name
        if twitter is not None:
            self.twitter = twitter
        if tiktok is not None:
            self.tiktok = tiktok
        self.id = id
        if consent_email is not None:
            self.consent_email = consent_email
        if longitude is not None:
            self.longitude = longitude

    @property
    def last_name(self):
        """Gets the last_name of this UserUpdateRequest.  # noqa: E501


        :return: The last_name of this UserUpdateRequest.  # noqa: E501
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this UserUpdateRequest.


        :param last_name: The last_name of this UserUpdateRequest.  # noqa: E501
        :type: str
        """

        self._last_name = last_name

    @property
    def website(self):
        """Gets the website of this UserUpdateRequest.  # noqa: E501


        :return: The website of this UserUpdateRequest.  # noqa: E501
        :rtype: str
        """
        return self._website

    @website.setter
    def website(self, website):
        """Sets the website of this UserUpdateRequest.


        :param website: The website of this UserUpdateRequest.  # noqa: E501
        :type: str
        """

        self._website = website

    @property
    def consent_privacy_policy(self):
        """Gets the consent_privacy_policy of this UserUpdateRequest.  # noqa: E501


        :return: The consent_privacy_policy of this UserUpdateRequest.  # noqa: E501
        :rtype: str
        """
        return self._consent_privacy_policy

    @consent_privacy_policy.setter
    def consent_privacy_policy(self, consent_privacy_policy):
        """Sets the consent_privacy_policy of this UserUpdateRequest.


        :param consent_privacy_policy: The consent_privacy_policy of this UserUpdateRequest.  # noqa: E501
        :type: str
        """

        self._consent_privacy_policy = consent_privacy_policy

    @property
    def display_name(self):
        """Gets the display_name of this UserUpdateRequest.  # noqa: E501


        :return: The display_name of this UserUpdateRequest.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this UserUpdateRequest.


        :param display_name: The display_name of this UserUpdateRequest.  # noqa: E501
        :type: str
        """

        self._display_name = display_name

    @property
    def latitude(self):
        """Gets the latitude of this UserUpdateRequest.  # noqa: E501


        :return: The latitude of this UserUpdateRequest.  # noqa: E501
        :rtype: float
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude):
        """Sets the latitude of this UserUpdateRequest.


        :param latitude: The latitude of this UserUpdateRequest.  # noqa: E501
        :type: float
        """

        self._latitude = latitude

    @property
    def newcoin_create_account(self):
        """Gets the newcoin_create_account of this UserUpdateRequest.  # noqa: E501


        :return: The newcoin_create_account of this UserUpdateRequest.  # noqa: E501
        :rtype: str
        """
        return self._newcoin_create_account

    @newcoin_create_account.setter
    def newcoin_create_account(self, newcoin_create_account):
        """Sets the newcoin_create_account of this UserUpdateRequest.


        :param newcoin_create_account: The newcoin_create_account of this UserUpdateRequest.  # noqa: E501
        :type: str
        """

        self._newcoin_create_account = newcoin_create_account

    @property
    def full_name(self):
        """Gets the full_name of this UserUpdateRequest.  # noqa: E501


        :return: The full_name of this UserUpdateRequest.  # noqa: E501
        :rtype: str
        """
        return self._full_name

    @full_name.setter
    def full_name(self, full_name):
        """Sets the full_name of this UserUpdateRequest.


        :param full_name: The full_name of this UserUpdateRequest.  # noqa: E501
        :type: str
        """

        self._full_name = full_name

    @property
    def tumblr(self):
        """Gets the tumblr of this UserUpdateRequest.  # noqa: E501


        :return: The tumblr of this UserUpdateRequest.  # noqa: E501
        :rtype: str
        """
        return self._tumblr

    @tumblr.setter
    def tumblr(self, tumblr):
        """Sets the tumblr of this UserUpdateRequest.


        :param tumblr: The tumblr of this UserUpdateRequest.  # noqa: E501
        :type: str
        """

        self._tumblr = tumblr

    @property
    def description(self):
        """Gets the description of this UserUpdateRequest.  # noqa: E501


        :return: The description of this UserUpdateRequest.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this UserUpdateRequest.


        :param description: The description of this UserUpdateRequest.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def instagram(self):
        """Gets the instagram of this UserUpdateRequest.  # noqa: E501


        :return: The instagram of this UserUpdateRequest.  # noqa: E501
        :rtype: str
        """
        return self._instagram

    @instagram.setter
    def instagram(self, instagram):
        """Sets the instagram of this UserUpdateRequest.


        :param instagram: The instagram of this UserUpdateRequest.  # noqa: E501
        :type: str
        """

        self._instagram = instagram

    @property
    def soundcloud(self):
        """Gets the soundcloud of this UserUpdateRequest.  # noqa: E501


        :return: The soundcloud of this UserUpdateRequest.  # noqa: E501
        :rtype: str
        """
        return self._soundcloud

    @soundcloud.setter
    def soundcloud(self, soundcloud):
        """Sets the soundcloud of this UserUpdateRequest.


        :param soundcloud: The soundcloud of this UserUpdateRequest.  # noqa: E501
        :type: str
        """

        self._soundcloud = soundcloud

    @property
    def first_name(self):
        """Gets the first_name of this UserUpdateRequest.  # noqa: E501


        :return: The first_name of this UserUpdateRequest.  # noqa: E501
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this UserUpdateRequest.


        :param first_name: The first_name of this UserUpdateRequest.  # noqa: E501
        :type: str
        """

        self._first_name = first_name

    @property
    def twitter(self):
        """Gets the twitter of this UserUpdateRequest.  # noqa: E501


        :return: The twitter of this UserUpdateRequest.  # noqa: E501
        :rtype: str
        """
        return self._twitter

    @twitter.setter
    def twitter(self, twitter):
        """Sets the twitter of this UserUpdateRequest.


        :param twitter: The twitter of this UserUpdateRequest.  # noqa: E501
        :type: str
        """

        self._twitter = twitter

    @property
    def tiktok(self):
        """Gets the tiktok of this UserUpdateRequest.  # noqa: E501


        :return: The tiktok of this UserUpdateRequest.  # noqa: E501
        :rtype: str
        """
        return self._tiktok

    @tiktok.setter
    def tiktok(self, tiktok):
        """Sets the tiktok of this UserUpdateRequest.


        :param tiktok: The tiktok of this UserUpdateRequest.  # noqa: E501
        :type: str
        """

        self._tiktok = tiktok

    @property
    def id(self):
        """Gets the id of this UserUpdateRequest.  # noqa: E501


        :return: The id of this UserUpdateRequest.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this UserUpdateRequest.


        :param id: The id of this UserUpdateRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def consent_email(self):
        """Gets the consent_email of this UserUpdateRequest.  # noqa: E501


        :return: The consent_email of this UserUpdateRequest.  # noqa: E501
        :rtype: str
        """
        return self._consent_email

    @consent_email.setter
    def consent_email(self, consent_email):
        """Sets the consent_email of this UserUpdateRequest.


        :param consent_email: The consent_email of this UserUpdateRequest.  # noqa: E501
        :type: str
        """

        self._consent_email = consent_email

    @property
    def longitude(self):
        """Gets the longitude of this UserUpdateRequest.  # noqa: E501


        :return: The longitude of this UserUpdateRequest.  # noqa: E501
        :rtype: float
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude):
        """Sets the longitude of this UserUpdateRequest.


        :param longitude: The longitude of this UserUpdateRequest.  # noqa: E501
        :type: float
        """

        self._longitude = longitude

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserUpdateRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserUpdateRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UserUpdateRequest):
            return True

        return self.to_dict() != other.to_dict()
