/*
 * newlife-creator-api-eu-dev
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2022-05-20T13:39:48Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PaymentStripePaymentIntentCreateRequestItems struct {
	ProductId string `json:"productId,omitempty"`
	PriceId string `json:"priceId,omitempty"`
}
