/*
 * newlife-creator-api-eu-dev
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2022-06-09T06:13:03Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PostCreateRequest struct {
	License string `json:"license,omitempty"`
	DoMint string `json:"doMint,omitempty"`
	Description string `json:"description,omitempty"`
	Embed string `json:"embed,omitempty"`
	Title string `json:"title,omitempty"`
	ContentType string `json:"contentType,omitempty"`
	Content string `json:"content,omitempty"`
}
