/*
 * newlife-creator-api-eu-dev
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2022-05-20T13:39:48Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type BcStakePoolRequest struct {
	Owner string `json:"owner"`
	PayerPrvKey string `json:"payer_prv_key"`
	Amt string `json:"amt"`
	Payer string `json:"payer"`
}
