/*
 * newlife-creator-api-eu-dev
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2022-06-09T06:13:03Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// BcApproveDaoProposalRequest Model
type BcApproveDaoProposalRequest struct {
	Approver string `json:"approver,omitempty"`
	ProposalAuthor string `json:"proposal_author,omitempty"`
	ProposalId string `json:"proposal_id,omitempty"`
	DaoId float32 `json:"dao_id,omitempty"`
	DaoOwner string `json:"dao_owner,omitempty"`
	ApproverPrvKey string `json:"approver_prv_key,omitempty"`
}
