/*
 * newlife-creator-api-eu-dev
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2022-05-20T13:39:48Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type UserUpdateRequest struct {
	LastName string `json:"lastName,omitempty"`
	Website string `json:"website,omitempty"`
	ConsentPrivacyPolicy string `json:"consentPrivacyPolicy,omitempty"`
	DisplayName string `json:"displayName,omitempty"`
	Latitude float32 `json:"latitude,omitempty"`
	NewcoinCreateAccount string `json:"newcoinCreateAccount,omitempty"`
	FullName string `json:"fullName,omitempty"`
	Tumblr string `json:"tumblr,omitempty"`
	Description string `json:"description,omitempty"`
	Instagram string `json:"instagram,omitempty"`
	Soundcloud string `json:"soundcloud,omitempty"`
	FirstName string `json:"firstName,omitempty"`
	Twitter string `json:"twitter,omitempty"`
	Tiktok string `json:"tiktok,omitempty"`
	Id string `json:"id"`
	ConsentEmail string `json:"consentEmail,omitempty"`
	Longitude float32 `json:"longitude,omitempty"`
}
