/*
 * newgraph-api-eu-dev
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2022-10-04T15:34:01Z
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * MoodPagedListReadPublicResponseAuthor
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-10-05T17:10:47.666Z")
public class MoodPagedListReadPublicResponseAuthor {
  @SerializedName("newcoinTicker")
  private String newcoinTicker = null;

  @SerializedName("youtube")
  private String youtube = null;

  @SerializedName("powered")
  private BigDecimal powered = null;

  @SerializedName("displayName")
  private String displayName = null;

  @SerializedName("newcoinAccTx")
  private String newcoinAccTx = null;

  @SerializedName("latitude")
  private BigDecimal latitude = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("newcoinPoolId")
  private String newcoinPoolId = null;

  @SerializedName("tumblr")
  private String tumblr = null;

  @SerializedName("aspectRatio")
  private BigDecimal aspectRatio = null;

  @SerializedName("instagram")
  private String instagram = null;

  @SerializedName("medium")
  private String medium = null;

  @SerializedName("newcoinActivePublicKey")
  private String newcoinActivePublicKey = null;

  @SerializedName("soundcloud")
  private String soundcloud = null;

  @SerializedName("newcoinPublicKey")
  private String newcoinPublicKey = null;

  @SerializedName("powering")
  private BigDecimal powering = null;

  @SerializedName("snapchat")
  private String snapchat = null;

  @SerializedName("apple")
  private String apple = null;

  @SerializedName("twitter")
  private String twitter = null;

  @SerializedName("newcoinOwnerPublicKey")
  private String newcoinOwnerPublicKey = null;

  @SerializedName("tiktok")
  private String tiktok = null;

  @SerializedName("reddit")
  private String reddit = null;

  @SerializedName("youtubeId")
  private String youtubeId = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("newcoinPoolStake")
  private BigDecimal newcoinPoolStake = null;

  @SerializedName("contentType")
  private String contentType = null;

  @SerializedName("signal")
  private String signal = null;

  @SerializedName("longitude")
  private BigDecimal longitude = null;

  @SerializedName("newcoinPublisherPublicKey")
  private String newcoinPublisherPublicKey = null;

  @SerializedName("website")
  private String website = null;

  @SerializedName("created")
  private String created = null;

  @SerializedName("spotify")
  private String spotify = null;

  @SerializedName("facebook")
  private String facebook = null;

  @SerializedName("facebookId")
  private String facebookId = null;

  @SerializedName("fullName")
  private String fullName = null;

  @SerializedName("telegram")
  private String telegram = null;

  @SerializedName("pinterest")
  private String pinterest = null;

  @SerializedName("verifiedSocialIds")
  private List<String> verifiedSocialIds = null;

  @SerializedName("newcoinPoolTx")
  private String newcoinPoolTx = null;

  @SerializedName("license")
  private String license = null;

  @SerializedName("contentUrl")
  private String contentUrl = null;

  @SerializedName("discord")
  private String discord = null;

  @SerializedName("blurHash")
  private String blurHash = null;

  @SerializedName("consentEmail")
  private String consentEmail = null;

  @SerializedName("updated")
  private String updated = null;

  @SerializedName("username")
  private String username = null;

  public MoodPagedListReadPublicResponseAuthor newcoinTicker(String newcoinTicker) {
    this.newcoinTicker = newcoinTicker;
    return this;
  }

   /**
   * Get newcoinTicker
   * @return newcoinTicker
  **/
  @ApiModelProperty(value = "")
  public String getNewcoinTicker() {
    return newcoinTicker;
  }

  public void setNewcoinTicker(String newcoinTicker) {
    this.newcoinTicker = newcoinTicker;
  }

  public MoodPagedListReadPublicResponseAuthor youtube(String youtube) {
    this.youtube = youtube;
    return this;
  }

   /**
   * Get youtube
   * @return youtube
  **/
  @ApiModelProperty(value = "")
  public String getYoutube() {
    return youtube;
  }

  public void setYoutube(String youtube) {
    this.youtube = youtube;
  }

  public MoodPagedListReadPublicResponseAuthor powered(BigDecimal powered) {
    this.powered = powered;
    return this;
  }

   /**
   * Get powered
   * @return powered
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getPowered() {
    return powered;
  }

  public void setPowered(BigDecimal powered) {
    this.powered = powered;
  }

  public MoodPagedListReadPublicResponseAuthor displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Get displayName
   * @return displayName
  **/
  @ApiModelProperty(value = "")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public MoodPagedListReadPublicResponseAuthor newcoinAccTx(String newcoinAccTx) {
    this.newcoinAccTx = newcoinAccTx;
    return this;
  }

   /**
   * Get newcoinAccTx
   * @return newcoinAccTx
  **/
  @ApiModelProperty(value = "")
  public String getNewcoinAccTx() {
    return newcoinAccTx;
  }

  public void setNewcoinAccTx(String newcoinAccTx) {
    this.newcoinAccTx = newcoinAccTx;
  }

  public MoodPagedListReadPublicResponseAuthor latitude(BigDecimal latitude) {
    this.latitude = latitude;
    return this;
  }

   /**
   * Get latitude
   * @return latitude
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getLatitude() {
    return latitude;
  }

  public void setLatitude(BigDecimal latitude) {
    this.latitude = latitude;
  }

  public MoodPagedListReadPublicResponseAuthor description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public MoodPagedListReadPublicResponseAuthor newcoinPoolId(String newcoinPoolId) {
    this.newcoinPoolId = newcoinPoolId;
    return this;
  }

   /**
   * Get newcoinPoolId
   * @return newcoinPoolId
  **/
  @ApiModelProperty(value = "")
  public String getNewcoinPoolId() {
    return newcoinPoolId;
  }

  public void setNewcoinPoolId(String newcoinPoolId) {
    this.newcoinPoolId = newcoinPoolId;
  }

  public MoodPagedListReadPublicResponseAuthor tumblr(String tumblr) {
    this.tumblr = tumblr;
    return this;
  }

   /**
   * Get tumblr
   * @return tumblr
  **/
  @ApiModelProperty(value = "")
  public String getTumblr() {
    return tumblr;
  }

  public void setTumblr(String tumblr) {
    this.tumblr = tumblr;
  }

  public MoodPagedListReadPublicResponseAuthor aspectRatio(BigDecimal aspectRatio) {
    this.aspectRatio = aspectRatio;
    return this;
  }

   /**
   * Get aspectRatio
   * @return aspectRatio
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getAspectRatio() {
    return aspectRatio;
  }

  public void setAspectRatio(BigDecimal aspectRatio) {
    this.aspectRatio = aspectRatio;
  }

  public MoodPagedListReadPublicResponseAuthor instagram(String instagram) {
    this.instagram = instagram;
    return this;
  }

   /**
   * Get instagram
   * @return instagram
  **/
  @ApiModelProperty(value = "")
  public String getInstagram() {
    return instagram;
  }

  public void setInstagram(String instagram) {
    this.instagram = instagram;
  }

  public MoodPagedListReadPublicResponseAuthor medium(String medium) {
    this.medium = medium;
    return this;
  }

   /**
   * Get medium
   * @return medium
  **/
  @ApiModelProperty(value = "")
  public String getMedium() {
    return medium;
  }

  public void setMedium(String medium) {
    this.medium = medium;
  }

  public MoodPagedListReadPublicResponseAuthor newcoinActivePublicKey(String newcoinActivePublicKey) {
    this.newcoinActivePublicKey = newcoinActivePublicKey;
    return this;
  }

   /**
   * Get newcoinActivePublicKey
   * @return newcoinActivePublicKey
  **/
  @ApiModelProperty(value = "")
  public String getNewcoinActivePublicKey() {
    return newcoinActivePublicKey;
  }

  public void setNewcoinActivePublicKey(String newcoinActivePublicKey) {
    this.newcoinActivePublicKey = newcoinActivePublicKey;
  }

  public MoodPagedListReadPublicResponseAuthor soundcloud(String soundcloud) {
    this.soundcloud = soundcloud;
    return this;
  }

   /**
   * Get soundcloud
   * @return soundcloud
  **/
  @ApiModelProperty(value = "")
  public String getSoundcloud() {
    return soundcloud;
  }

  public void setSoundcloud(String soundcloud) {
    this.soundcloud = soundcloud;
  }

  public MoodPagedListReadPublicResponseAuthor newcoinPublicKey(String newcoinPublicKey) {
    this.newcoinPublicKey = newcoinPublicKey;
    return this;
  }

   /**
   * Get newcoinPublicKey
   * @return newcoinPublicKey
  **/
  @ApiModelProperty(value = "")
  public String getNewcoinPublicKey() {
    return newcoinPublicKey;
  }

  public void setNewcoinPublicKey(String newcoinPublicKey) {
    this.newcoinPublicKey = newcoinPublicKey;
  }

  public MoodPagedListReadPublicResponseAuthor powering(BigDecimal powering) {
    this.powering = powering;
    return this;
  }

   /**
   * Get powering
   * @return powering
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getPowering() {
    return powering;
  }

  public void setPowering(BigDecimal powering) {
    this.powering = powering;
  }

  public MoodPagedListReadPublicResponseAuthor snapchat(String snapchat) {
    this.snapchat = snapchat;
    return this;
  }

   /**
   * Get snapchat
   * @return snapchat
  **/
  @ApiModelProperty(value = "")
  public String getSnapchat() {
    return snapchat;
  }

  public void setSnapchat(String snapchat) {
    this.snapchat = snapchat;
  }

  public MoodPagedListReadPublicResponseAuthor apple(String apple) {
    this.apple = apple;
    return this;
  }

   /**
   * Get apple
   * @return apple
  **/
  @ApiModelProperty(value = "")
  public String getApple() {
    return apple;
  }

  public void setApple(String apple) {
    this.apple = apple;
  }

  public MoodPagedListReadPublicResponseAuthor twitter(String twitter) {
    this.twitter = twitter;
    return this;
  }

   /**
   * Get twitter
   * @return twitter
  **/
  @ApiModelProperty(value = "")
  public String getTwitter() {
    return twitter;
  }

  public void setTwitter(String twitter) {
    this.twitter = twitter;
  }

  public MoodPagedListReadPublicResponseAuthor newcoinOwnerPublicKey(String newcoinOwnerPublicKey) {
    this.newcoinOwnerPublicKey = newcoinOwnerPublicKey;
    return this;
  }

   /**
   * Get newcoinOwnerPublicKey
   * @return newcoinOwnerPublicKey
  **/
  @ApiModelProperty(value = "")
  public String getNewcoinOwnerPublicKey() {
    return newcoinOwnerPublicKey;
  }

  public void setNewcoinOwnerPublicKey(String newcoinOwnerPublicKey) {
    this.newcoinOwnerPublicKey = newcoinOwnerPublicKey;
  }

  public MoodPagedListReadPublicResponseAuthor tiktok(String tiktok) {
    this.tiktok = tiktok;
    return this;
  }

   /**
   * Get tiktok
   * @return tiktok
  **/
  @ApiModelProperty(value = "")
  public String getTiktok() {
    return tiktok;
  }

  public void setTiktok(String tiktok) {
    this.tiktok = tiktok;
  }

  public MoodPagedListReadPublicResponseAuthor reddit(String reddit) {
    this.reddit = reddit;
    return this;
  }

   /**
   * Get reddit
   * @return reddit
  **/
  @ApiModelProperty(value = "")
  public String getReddit() {
    return reddit;
  }

  public void setReddit(String reddit) {
    this.reddit = reddit;
  }

  public MoodPagedListReadPublicResponseAuthor youtubeId(String youtubeId) {
    this.youtubeId = youtubeId;
    return this;
  }

   /**
   * Get youtubeId
   * @return youtubeId
  **/
  @ApiModelProperty(value = "")
  public String getYoutubeId() {
    return youtubeId;
  }

  public void setYoutubeId(String youtubeId) {
    this.youtubeId = youtubeId;
  }

  public MoodPagedListReadPublicResponseAuthor id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public MoodPagedListReadPublicResponseAuthor newcoinPoolStake(BigDecimal newcoinPoolStake) {
    this.newcoinPoolStake = newcoinPoolStake;
    return this;
  }

   /**
   * Get newcoinPoolStake
   * @return newcoinPoolStake
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getNewcoinPoolStake() {
    return newcoinPoolStake;
  }

  public void setNewcoinPoolStake(BigDecimal newcoinPoolStake) {
    this.newcoinPoolStake = newcoinPoolStake;
  }

  public MoodPagedListReadPublicResponseAuthor contentType(String contentType) {
    this.contentType = contentType;
    return this;
  }

   /**
   * Get contentType
   * @return contentType
  **/
  @ApiModelProperty(value = "")
  public String getContentType() {
    return contentType;
  }

  public void setContentType(String contentType) {
    this.contentType = contentType;
  }

  public MoodPagedListReadPublicResponseAuthor signal(String signal) {
    this.signal = signal;
    return this;
  }

   /**
   * Get signal
   * @return signal
  **/
  @ApiModelProperty(value = "")
  public String getSignal() {
    return signal;
  }

  public void setSignal(String signal) {
    this.signal = signal;
  }

  public MoodPagedListReadPublicResponseAuthor longitude(BigDecimal longitude) {
    this.longitude = longitude;
    return this;
  }

   /**
   * Get longitude
   * @return longitude
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getLongitude() {
    return longitude;
  }

  public void setLongitude(BigDecimal longitude) {
    this.longitude = longitude;
  }

  public MoodPagedListReadPublicResponseAuthor newcoinPublisherPublicKey(String newcoinPublisherPublicKey) {
    this.newcoinPublisherPublicKey = newcoinPublisherPublicKey;
    return this;
  }

   /**
   * Get newcoinPublisherPublicKey
   * @return newcoinPublisherPublicKey
  **/
  @ApiModelProperty(value = "")
  public String getNewcoinPublisherPublicKey() {
    return newcoinPublisherPublicKey;
  }

  public void setNewcoinPublisherPublicKey(String newcoinPublisherPublicKey) {
    this.newcoinPublisherPublicKey = newcoinPublisherPublicKey;
  }

  public MoodPagedListReadPublicResponseAuthor website(String website) {
    this.website = website;
    return this;
  }

   /**
   * Get website
   * @return website
  **/
  @ApiModelProperty(value = "")
  public String getWebsite() {
    return website;
  }

  public void setWebsite(String website) {
    this.website = website;
  }

  public MoodPagedListReadPublicResponseAuthor created(String created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @ApiModelProperty(value = "")
  public String getCreated() {
    return created;
  }

  public void setCreated(String created) {
    this.created = created;
  }

  public MoodPagedListReadPublicResponseAuthor spotify(String spotify) {
    this.spotify = spotify;
    return this;
  }

   /**
   * Get spotify
   * @return spotify
  **/
  @ApiModelProperty(value = "")
  public String getSpotify() {
    return spotify;
  }

  public void setSpotify(String spotify) {
    this.spotify = spotify;
  }

  public MoodPagedListReadPublicResponseAuthor facebook(String facebook) {
    this.facebook = facebook;
    return this;
  }

   /**
   * Get facebook
   * @return facebook
  **/
  @ApiModelProperty(value = "")
  public String getFacebook() {
    return facebook;
  }

  public void setFacebook(String facebook) {
    this.facebook = facebook;
  }

  public MoodPagedListReadPublicResponseAuthor facebookId(String facebookId) {
    this.facebookId = facebookId;
    return this;
  }

   /**
   * Get facebookId
   * @return facebookId
  **/
  @ApiModelProperty(value = "")
  public String getFacebookId() {
    return facebookId;
  }

  public void setFacebookId(String facebookId) {
    this.facebookId = facebookId;
  }

  public MoodPagedListReadPublicResponseAuthor fullName(String fullName) {
    this.fullName = fullName;
    return this;
  }

   /**
   * Get fullName
   * @return fullName
  **/
  @ApiModelProperty(value = "")
  public String getFullName() {
    return fullName;
  }

  public void setFullName(String fullName) {
    this.fullName = fullName;
  }

  public MoodPagedListReadPublicResponseAuthor telegram(String telegram) {
    this.telegram = telegram;
    return this;
  }

   /**
   * Get telegram
   * @return telegram
  **/
  @ApiModelProperty(value = "")
  public String getTelegram() {
    return telegram;
  }

  public void setTelegram(String telegram) {
    this.telegram = telegram;
  }

  public MoodPagedListReadPublicResponseAuthor pinterest(String pinterest) {
    this.pinterest = pinterest;
    return this;
  }

   /**
   * Get pinterest
   * @return pinterest
  **/
  @ApiModelProperty(value = "")
  public String getPinterest() {
    return pinterest;
  }

  public void setPinterest(String pinterest) {
    this.pinterest = pinterest;
  }

  public MoodPagedListReadPublicResponseAuthor verifiedSocialIds(List<String> verifiedSocialIds) {
    this.verifiedSocialIds = verifiedSocialIds;
    return this;
  }

  public MoodPagedListReadPublicResponseAuthor addVerifiedSocialIdsItem(String verifiedSocialIdsItem) {
    if (this.verifiedSocialIds == null) {
      this.verifiedSocialIds = new ArrayList<String>();
    }
    this.verifiedSocialIds.add(verifiedSocialIdsItem);
    return this;
  }

   /**
   * Get verifiedSocialIds
   * @return verifiedSocialIds
  **/
  @ApiModelProperty(value = "")
  public List<String> getVerifiedSocialIds() {
    return verifiedSocialIds;
  }

  public void setVerifiedSocialIds(List<String> verifiedSocialIds) {
    this.verifiedSocialIds = verifiedSocialIds;
  }

  public MoodPagedListReadPublicResponseAuthor newcoinPoolTx(String newcoinPoolTx) {
    this.newcoinPoolTx = newcoinPoolTx;
    return this;
  }

   /**
   * Get newcoinPoolTx
   * @return newcoinPoolTx
  **/
  @ApiModelProperty(value = "")
  public String getNewcoinPoolTx() {
    return newcoinPoolTx;
  }

  public void setNewcoinPoolTx(String newcoinPoolTx) {
    this.newcoinPoolTx = newcoinPoolTx;
  }

  public MoodPagedListReadPublicResponseAuthor license(String license) {
    this.license = license;
    return this;
  }

   /**
   * Get license
   * @return license
  **/
  @ApiModelProperty(value = "")
  public String getLicense() {
    return license;
  }

  public void setLicense(String license) {
    this.license = license;
  }

  public MoodPagedListReadPublicResponseAuthor contentUrl(String contentUrl) {
    this.contentUrl = contentUrl;
    return this;
  }

   /**
   * Get contentUrl
   * @return contentUrl
  **/
  @ApiModelProperty(value = "")
  public String getContentUrl() {
    return contentUrl;
  }

  public void setContentUrl(String contentUrl) {
    this.contentUrl = contentUrl;
  }

  public MoodPagedListReadPublicResponseAuthor discord(String discord) {
    this.discord = discord;
    return this;
  }

   /**
   * Get discord
   * @return discord
  **/
  @ApiModelProperty(value = "")
  public String getDiscord() {
    return discord;
  }

  public void setDiscord(String discord) {
    this.discord = discord;
  }

  public MoodPagedListReadPublicResponseAuthor blurHash(String blurHash) {
    this.blurHash = blurHash;
    return this;
  }

   /**
   * Get blurHash
   * @return blurHash
  **/
  @ApiModelProperty(value = "")
  public String getBlurHash() {
    return blurHash;
  }

  public void setBlurHash(String blurHash) {
    this.blurHash = blurHash;
  }

  public MoodPagedListReadPublicResponseAuthor consentEmail(String consentEmail) {
    this.consentEmail = consentEmail;
    return this;
  }

   /**
   * Get consentEmail
   * @return consentEmail
  **/
  @ApiModelProperty(value = "")
  public String getConsentEmail() {
    return consentEmail;
  }

  public void setConsentEmail(String consentEmail) {
    this.consentEmail = consentEmail;
  }

  public MoodPagedListReadPublicResponseAuthor updated(String updated) {
    this.updated = updated;
    return this;
  }

   /**
   * Get updated
   * @return updated
  **/
  @ApiModelProperty(value = "")
  public String getUpdated() {
    return updated;
  }

  public void setUpdated(String updated) {
    this.updated = updated;
  }

  public MoodPagedListReadPublicResponseAuthor username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/
  @ApiModelProperty(value = "")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MoodPagedListReadPublicResponseAuthor moodPagedListReadPublicResponseAuthor = (MoodPagedListReadPublicResponseAuthor) o;
    return Objects.equals(this.newcoinTicker, moodPagedListReadPublicResponseAuthor.newcoinTicker) &&
        Objects.equals(this.youtube, moodPagedListReadPublicResponseAuthor.youtube) &&
        Objects.equals(this.powered, moodPagedListReadPublicResponseAuthor.powered) &&
        Objects.equals(this.displayName, moodPagedListReadPublicResponseAuthor.displayName) &&
        Objects.equals(this.newcoinAccTx, moodPagedListReadPublicResponseAuthor.newcoinAccTx) &&
        Objects.equals(this.latitude, moodPagedListReadPublicResponseAuthor.latitude) &&
        Objects.equals(this.description, moodPagedListReadPublicResponseAuthor.description) &&
        Objects.equals(this.newcoinPoolId, moodPagedListReadPublicResponseAuthor.newcoinPoolId) &&
        Objects.equals(this.tumblr, moodPagedListReadPublicResponseAuthor.tumblr) &&
        Objects.equals(this.aspectRatio, moodPagedListReadPublicResponseAuthor.aspectRatio) &&
        Objects.equals(this.instagram, moodPagedListReadPublicResponseAuthor.instagram) &&
        Objects.equals(this.medium, moodPagedListReadPublicResponseAuthor.medium) &&
        Objects.equals(this.newcoinActivePublicKey, moodPagedListReadPublicResponseAuthor.newcoinActivePublicKey) &&
        Objects.equals(this.soundcloud, moodPagedListReadPublicResponseAuthor.soundcloud) &&
        Objects.equals(this.newcoinPublicKey, moodPagedListReadPublicResponseAuthor.newcoinPublicKey) &&
        Objects.equals(this.powering, moodPagedListReadPublicResponseAuthor.powering) &&
        Objects.equals(this.snapchat, moodPagedListReadPublicResponseAuthor.snapchat) &&
        Objects.equals(this.apple, moodPagedListReadPublicResponseAuthor.apple) &&
        Objects.equals(this.twitter, moodPagedListReadPublicResponseAuthor.twitter) &&
        Objects.equals(this.newcoinOwnerPublicKey, moodPagedListReadPublicResponseAuthor.newcoinOwnerPublicKey) &&
        Objects.equals(this.tiktok, moodPagedListReadPublicResponseAuthor.tiktok) &&
        Objects.equals(this.reddit, moodPagedListReadPublicResponseAuthor.reddit) &&
        Objects.equals(this.youtubeId, moodPagedListReadPublicResponseAuthor.youtubeId) &&
        Objects.equals(this.id, moodPagedListReadPublicResponseAuthor.id) &&
        Objects.equals(this.newcoinPoolStake, moodPagedListReadPublicResponseAuthor.newcoinPoolStake) &&
        Objects.equals(this.contentType, moodPagedListReadPublicResponseAuthor.contentType) &&
        Objects.equals(this.signal, moodPagedListReadPublicResponseAuthor.signal) &&
        Objects.equals(this.longitude, moodPagedListReadPublicResponseAuthor.longitude) &&
        Objects.equals(this.newcoinPublisherPublicKey, moodPagedListReadPublicResponseAuthor.newcoinPublisherPublicKey) &&
        Objects.equals(this.website, moodPagedListReadPublicResponseAuthor.website) &&
        Objects.equals(this.created, moodPagedListReadPublicResponseAuthor.created) &&
        Objects.equals(this.spotify, moodPagedListReadPublicResponseAuthor.spotify) &&
        Objects.equals(this.facebook, moodPagedListReadPublicResponseAuthor.facebook) &&
        Objects.equals(this.facebookId, moodPagedListReadPublicResponseAuthor.facebookId) &&
        Objects.equals(this.fullName, moodPagedListReadPublicResponseAuthor.fullName) &&
        Objects.equals(this.telegram, moodPagedListReadPublicResponseAuthor.telegram) &&
        Objects.equals(this.pinterest, moodPagedListReadPublicResponseAuthor.pinterest) &&
        Objects.equals(this.verifiedSocialIds, moodPagedListReadPublicResponseAuthor.verifiedSocialIds) &&
        Objects.equals(this.newcoinPoolTx, moodPagedListReadPublicResponseAuthor.newcoinPoolTx) &&
        Objects.equals(this.license, moodPagedListReadPublicResponseAuthor.license) &&
        Objects.equals(this.contentUrl, moodPagedListReadPublicResponseAuthor.contentUrl) &&
        Objects.equals(this.discord, moodPagedListReadPublicResponseAuthor.discord) &&
        Objects.equals(this.blurHash, moodPagedListReadPublicResponseAuthor.blurHash) &&
        Objects.equals(this.consentEmail, moodPagedListReadPublicResponseAuthor.consentEmail) &&
        Objects.equals(this.updated, moodPagedListReadPublicResponseAuthor.updated) &&
        Objects.equals(this.username, moodPagedListReadPublicResponseAuthor.username);
  }

  @Override
  public int hashCode() {
    return Objects.hash(newcoinTicker, youtube, powered, displayName, newcoinAccTx, latitude, description, newcoinPoolId, tumblr, aspectRatio, instagram, medium, newcoinActivePublicKey, soundcloud, newcoinPublicKey, powering, snapchat, apple, twitter, newcoinOwnerPublicKey, tiktok, reddit, youtubeId, id, newcoinPoolStake, contentType, signal, longitude, newcoinPublisherPublicKey, website, created, spotify, facebook, facebookId, fullName, telegram, pinterest, verifiedSocialIds, newcoinPoolTx, license, contentUrl, discord, blurHash, consentEmail, updated, username);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MoodPagedListReadPublicResponseAuthor {\n");
    
    sb.append("    newcoinTicker: ").append(toIndentedString(newcoinTicker)).append("\n");
    sb.append("    youtube: ").append(toIndentedString(youtube)).append("\n");
    sb.append("    powered: ").append(toIndentedString(powered)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    newcoinAccTx: ").append(toIndentedString(newcoinAccTx)).append("\n");
    sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    newcoinPoolId: ").append(toIndentedString(newcoinPoolId)).append("\n");
    sb.append("    tumblr: ").append(toIndentedString(tumblr)).append("\n");
    sb.append("    aspectRatio: ").append(toIndentedString(aspectRatio)).append("\n");
    sb.append("    instagram: ").append(toIndentedString(instagram)).append("\n");
    sb.append("    medium: ").append(toIndentedString(medium)).append("\n");
    sb.append("    newcoinActivePublicKey: ").append(toIndentedString(newcoinActivePublicKey)).append("\n");
    sb.append("    soundcloud: ").append(toIndentedString(soundcloud)).append("\n");
    sb.append("    newcoinPublicKey: ").append(toIndentedString(newcoinPublicKey)).append("\n");
    sb.append("    powering: ").append(toIndentedString(powering)).append("\n");
    sb.append("    snapchat: ").append(toIndentedString(snapchat)).append("\n");
    sb.append("    apple: ").append(toIndentedString(apple)).append("\n");
    sb.append("    twitter: ").append(toIndentedString(twitter)).append("\n");
    sb.append("    newcoinOwnerPublicKey: ").append(toIndentedString(newcoinOwnerPublicKey)).append("\n");
    sb.append("    tiktok: ").append(toIndentedString(tiktok)).append("\n");
    sb.append("    reddit: ").append(toIndentedString(reddit)).append("\n");
    sb.append("    youtubeId: ").append(toIndentedString(youtubeId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    newcoinPoolStake: ").append(toIndentedString(newcoinPoolStake)).append("\n");
    sb.append("    contentType: ").append(toIndentedString(contentType)).append("\n");
    sb.append("    signal: ").append(toIndentedString(signal)).append("\n");
    sb.append("    longitude: ").append(toIndentedString(longitude)).append("\n");
    sb.append("    newcoinPublisherPublicKey: ").append(toIndentedString(newcoinPublisherPublicKey)).append("\n");
    sb.append("    website: ").append(toIndentedString(website)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    spotify: ").append(toIndentedString(spotify)).append("\n");
    sb.append("    facebook: ").append(toIndentedString(facebook)).append("\n");
    sb.append("    facebookId: ").append(toIndentedString(facebookId)).append("\n");
    sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
    sb.append("    telegram: ").append(toIndentedString(telegram)).append("\n");
    sb.append("    pinterest: ").append(toIndentedString(pinterest)).append("\n");
    sb.append("    verifiedSocialIds: ").append(toIndentedString(verifiedSocialIds)).append("\n");
    sb.append("    newcoinPoolTx: ").append(toIndentedString(newcoinPoolTx)).append("\n");
    sb.append("    license: ").append(toIndentedString(license)).append("\n");
    sb.append("    contentUrl: ").append(toIndentedString(contentUrl)).append("\n");
    sb.append("    discord: ").append(toIndentedString(discord)).append("\n");
    sb.append("    blurHash: ").append(toIndentedString(blurHash)).append("\n");
    sb.append("    consentEmail: ").append(toIndentedString(consentEmail)).append("\n");
    sb.append("    updated: ").append(toIndentedString(updated)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

