/*
 * newlife-creator-api-eu-dev
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2022-05-20T13:39:48Z
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.PostTagsSearchPublicResponseValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * PostTagsSearchPublicResponse Model
 */
@ApiModel(description = "PostTagsSearchPublicResponse Model")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-05-24T15:32:28.129Z")
public class PostTagsSearchPublicResponse {
  @SerializedName("done")
  private Object done = null;

  @SerializedName("value")
  private List<PostTagsSearchPublicResponseValue> value = null;

  public PostTagsSearchPublicResponse done(Object done) {
    this.done = done;
    return this;
  }

   /**
   * Get done
   * @return done
  **/
  @ApiModelProperty(value = "")
  public Object getDone() {
    return done;
  }

  public void setDone(Object done) {
    this.done = done;
  }

  public PostTagsSearchPublicResponse value(List<PostTagsSearchPublicResponseValue> value) {
    this.value = value;
    return this;
  }

  public PostTagsSearchPublicResponse addValueItem(PostTagsSearchPublicResponseValue valueItem) {
    if (this.value == null) {
      this.value = new ArrayList<PostTagsSearchPublicResponseValue>();
    }
    this.value.add(valueItem);
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @ApiModelProperty(value = "")
  public List<PostTagsSearchPublicResponseValue> getValue() {
    return value;
  }

  public void setValue(List<PostTagsSearchPublicResponseValue> value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostTagsSearchPublicResponse postTagsSearchPublicResponse = (PostTagsSearchPublicResponse) o;
    return Objects.equals(this.done, postTagsSearchPublicResponse.done) &&
        Objects.equals(this.value, postTagsSearchPublicResponse.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(done, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostTagsSearchPublicResponse {\n");
    
    sb.append("    done: ").append(toIndentedString(done)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

