# coding: utf-8

"""
    newlife-creator-api-eu-dev

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2022-05-20T13:39:48Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.upload_request import UploadRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestUploadRequest(unittest.TestCase):
    """UploadRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUploadRequest(self):
        """Test UploadRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.upload_request.UploadRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
