# coding: utf-8

"""
    newgraph-api-eu-dev

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2022-10-04T15:34:01Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.user_invitation_read_public_response import UserInvitationReadPublicResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestUserInvitationReadPublicResponse(unittest.TestCase):
    """UserInvitationReadPublicResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserInvitationReadPublicResponse(self):
        """Test UserInvitationReadPublicResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.user_invitation_read_public_response.UserInvitationReadPublicResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
