/* 
 * newgraph-api-eu-dev
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2022-10-04T15:34:01Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct BcCreateDaoResponse {
  #[serde(rename = "TxID_createDao")]
  tx_id_create_dao: Option<String>,
  #[serde(rename = "dao_id")]
  dao_id: Option<String>
}

impl BcCreateDaoResponse {
  pub fn new() -> BcCreateDaoResponse {
    BcCreateDaoResponse {
      tx_id_create_dao: None,
      dao_id: None
    }
  }

  pub fn set_tx_id_create_dao(&mut self, tx_id_create_dao: String) {
    self.tx_id_create_dao = Some(tx_id_create_dao);
  }

  pub fn with_tx_id_create_dao(mut self, tx_id_create_dao: String) -> BcCreateDaoResponse {
    self.tx_id_create_dao = Some(tx_id_create_dao);
    self
  }

  pub fn tx_id_create_dao(&self) -> Option<&String> {
    self.tx_id_create_dao.as_ref()
  }

  pub fn reset_tx_id_create_dao(&mut self) {
    self.tx_id_create_dao = None;
  }

  pub fn set_dao_id(&mut self, dao_id: String) {
    self.dao_id = Some(dao_id);
  }

  pub fn with_dao_id(mut self, dao_id: String) -> BcCreateDaoResponse {
    self.dao_id = Some(dao_id);
    self
  }

  pub fn dao_id(&self) -> Option<&String> {
    self.dao_id.as_ref()
  }

  pub fn reset_dao_id(&mut self) {
    self.dao_id = None;
  }

}



