=begin
#newgraph-api-eu-dev

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2022-10-04T15:34:01Z

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.27

=end

require 'date'

module SwaggerClient
  class UserInviteRequest
    attr_accessor :youtube

    attr_accessor :spotify

    attr_accessor :facebook

    attr_accessor :full_name

    attr_accessor :tumblr

    attr_accessor :telegram

    attr_accessor :pinterest

    attr_accessor :instagram

    attr_accessor :medium

    attr_accessor :soundcloud

    attr_accessor :snapchat

    attr_accessor :apple

    attr_accessor :twitter

    attr_accessor :discord

    attr_accessor :phone

    attr_accessor :tiktok

    attr_accessor :reddit

    attr_accessor :signal

    attr_accessor :email

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'youtube' => :'youtube',
        :'spotify' => :'spotify',
        :'facebook' => :'facebook',
        :'full_name' => :'fullName',
        :'tumblr' => :'tumblr',
        :'telegram' => :'telegram',
        :'pinterest' => :'pinterest',
        :'instagram' => :'instagram',
        :'medium' => :'medium',
        :'soundcloud' => :'soundcloud',
        :'snapchat' => :'snapchat',
        :'apple' => :'apple',
        :'twitter' => :'twitter',
        :'discord' => :'discord',
        :'phone' => :'phone',
        :'tiktok' => :'tiktok',
        :'reddit' => :'reddit',
        :'signal' => :'signal',
        :'email' => :'email'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'youtube' => :'String',
        :'spotify' => :'String',
        :'facebook' => :'String',
        :'full_name' => :'String',
        :'tumblr' => :'String',
        :'telegram' => :'String',
        :'pinterest' => :'String',
        :'instagram' => :'String',
        :'medium' => :'String',
        :'soundcloud' => :'String',
        :'snapchat' => :'String',
        :'apple' => :'String',
        :'twitter' => :'String',
        :'discord' => :'String',
        :'phone' => :'String',
        :'tiktok' => :'String',
        :'reddit' => :'String',
        :'signal' => :'String',
        :'email' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'youtube')
        self.youtube = attributes[:'youtube']
      end

      if attributes.has_key?(:'spotify')
        self.spotify = attributes[:'spotify']
      end

      if attributes.has_key?(:'facebook')
        self.facebook = attributes[:'facebook']
      end

      if attributes.has_key?(:'fullName')
        self.full_name = attributes[:'fullName']
      end

      if attributes.has_key?(:'tumblr')
        self.tumblr = attributes[:'tumblr']
      end

      if attributes.has_key?(:'telegram')
        self.telegram = attributes[:'telegram']
      end

      if attributes.has_key?(:'pinterest')
        self.pinterest = attributes[:'pinterest']
      end

      if attributes.has_key?(:'instagram')
        self.instagram = attributes[:'instagram']
      end

      if attributes.has_key?(:'medium')
        self.medium = attributes[:'medium']
      end

      if attributes.has_key?(:'soundcloud')
        self.soundcloud = attributes[:'soundcloud']
      end

      if attributes.has_key?(:'snapchat')
        self.snapchat = attributes[:'snapchat']
      end

      if attributes.has_key?(:'apple')
        self.apple = attributes[:'apple']
      end

      if attributes.has_key?(:'twitter')
        self.twitter = attributes[:'twitter']
      end

      if attributes.has_key?(:'discord')
        self.discord = attributes[:'discord']
      end

      if attributes.has_key?(:'phone')
        self.phone = attributes[:'phone']
      end

      if attributes.has_key?(:'tiktok')
        self.tiktok = attributes[:'tiktok']
      end

      if attributes.has_key?(:'reddit')
        self.reddit = attributes[:'reddit']
      end

      if attributes.has_key?(:'signal')
        self.signal = attributes[:'signal']
      end

      if attributes.has_key?(:'email')
        self.email = attributes[:'email']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @full_name.nil?
        invalid_properties.push('invalid value for "full_name", full_name cannot be nil.')
      end

      if @phone.nil?
        invalid_properties.push('invalid value for "phone", phone cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @full_name.nil?
      return false if @phone.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          youtube == o.youtube &&
          spotify == o.spotify &&
          facebook == o.facebook &&
          full_name == o.full_name &&
          tumblr == o.tumblr &&
          telegram == o.telegram &&
          pinterest == o.pinterest &&
          instagram == o.instagram &&
          medium == o.medium &&
          soundcloud == o.soundcloud &&
          snapchat == o.snapchat &&
          apple == o.apple &&
          twitter == o.twitter &&
          discord == o.discord &&
          phone == o.phone &&
          tiktok == o.tiktok &&
          reddit == o.reddit &&
          signal == o.signal &&
          email == o.email
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [youtube, spotify, facebook, full_name, tumblr, telegram, pinterest, instagram, medium, soundcloud, snapchat, apple, twitter, discord, phone, tiktok, reddit, signal, email].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = SwaggerClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
